Q.1- Import the libraries and dataset. Print the head and shape of dataset. 

In [1]:
# import the Libraries
import numpy as np
import pandas as pd


In [5]:
data=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/balance-scale/balance-scale.data ')
data.head()

B  1  1.1  1.2  1.3
0  R  1    1    1    2
1  R  1    1    1    3
2  R  1    1    1    4
3  R  1    1    1    5
4  R  1    1    2    1

In [10]:
 print (data.shape)

(624, 5)


In [11]:
data.columns

Index(['B', '1', '1.1', '1.2', '1.3'], dtype='object')

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 624 entries, 0 to 623
Data columns (total 5 columns):
B      624 non-null object
1      624 non-null int64
1.1    624 non-null int64
1.2    624 non-null int64
1.3    624 non-null int64
dtypes: int64(4), object(1)
memory usage: 24.5+ KB


In [13]:
data.index

RangeIndex(start=0, stop=624, step=1)

Q.2- Slice the dataset. Save the first column as y(Target) and rest of the columns as X(Features). 

In [17]:
X = data.values[:, 1:5]
Y = data.values[:,0]

Q.3- Split the dataset by using train_test_split(). 

In [18]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, Y_train, Y_test= tts(X , Y, test_size=0.3, random_state=42)

Q.4- Use DecisionTree with criterion 

a. Gini

b. Entropy

Print the accuracy score. 

In [22]:
from sklearn.tree import DecisionTreeClassifier

clf_gini = DecisionTreeClassifier(criterion = "gini")
clf_gini.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [23]:
Y_pred = clf_gini.predict(X_test)

In [24]:
result = pd.DataFrame({'Actual': Y_test, 'Predicted':Y_pred})
print(result)

    Actual Predicted
0        R         B
1        L         L
2        B         L
3        R         R
4        L         L
5        L         L
6        R         R
7        B         L
8        L         L
9        R         R
10       R         R
11       R         R
12       R         B
13       R         R
14       L         L
15       L         L
16       R         R
17       R         R
18       R         R
19       L         L
20       R         R
21       R         R
22       L         L
23       L         L
24       R         B
25       R         R
26       R         R
27       L         L
28       L         L
29       R         R
..     ...       ...
158      R         R
159      L         L
160      L         L
161      R         R
162      R         R
163      L         L
164      L         L
165      L         L
166      R         R
167      L         L
168      R         R
169      R         R
170      L         L
171      R         R
172      L         B
173      R   

In [25]:
from sklearn.metrics import confusion_matrix as cm, classification_report as cr
print(cm(Y_test, Y_pred))
print(cr(Y_test, Y_pred))

[[ 1  8  3]
 [12 75  0]
 [11  3 75]]
             precision    recall  f1-score   support

          B       0.04      0.08      0.06        12
          L       0.87      0.86      0.87        87
          R       0.96      0.84      0.90        89

avg / total       0.86      0.80      0.83       188



In [30]:
from sklearn.metrics import accuracy_score
# Print Accuracy Score
print( 'Accuracy is ', accuracy_score(Y_test,Y_pred)*100)

Accuracy is  80.31914893617021


In [31]:
clf_entropy = DecisionTreeClassifier(criterion = "entropy")
clf_entropy.fit(X_train, Y_train)


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [36]:
Y_pred_en = clf_entropy.predict(X_test)

In [38]:
result = pd.DataFrame({'Actual': Y_test, 'Predicted':Y_pred_en})
print(result)

    Actual Predicted
0        R         B
1        L         L
2        B         L
3        R         R
4        L         L
5        L         L
6        R         R
7        B         L
8        L         L
9        R         R
10       R         R
11       R         R
12       R         L
13       R         R
14       L         L
15       L         L
16       R         R
17       R         R
18       R         R
19       L         L
20       R         R
21       R         R
22       L         L
23       L         L
24       R         B
25       R         R
26       R         R
27       L         L
28       L         L
29       R         R
..     ...       ...
158      R         R
159      L         L
160      L         L
161      R         R
162      R         R
163      L         L
164      L         L
165      L         L
166      R         R
167      L         L
168      R         R
169      R         R
170      L         L
171      R         R
172      L         B
173      R   

In [40]:
print(cm(Y_test, Y_pred_en))
print(cr(Y_test, Y_pred_en))

[[ 2  7  3]
 [14 72  1]
 [10  4 75]]
             precision    recall  f1-score   support

          B       0.08      0.17      0.11        12
          L       0.87      0.83      0.85        87
          R       0.95      0.84      0.89        89

avg / total       0.86      0.79      0.82       188



In [41]:
# Print Accuracy Score
print( "Accuracy is ", accuracy_score(Y_test,Y_pred_en)*100)

Accuracy is  79.25531914893617


Q.5- Use RandomForset with criterion 

a. Gini
b. Entropy

Print the accuracy score. 

In [61]:

from sklearn.ensemble import RandomForestClassifier
model_gini = RandomForestClassifier(criterion = "gini")
model_gini.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [62]:
Y_pred_rfc = model_gini.predict(X_test)

In [63]:
result = pd.DataFrame({'Actual': Y_test, 'Predicted':Y_pred_rfc})
print(result)

    Actual Predicted
0        R         L
1        L         L
2        B         L
3        R         R
4        L         L
5        L         L
6        R         R
7        B         R
8        L         L
9        R         R
10       R         R
11       R         R
12       R         L
13       R         R
14       L         L
15       L         B
16       R         R
17       R         R
18       R         R
19       L         L
20       R         R
21       R         R
22       L         L
23       L         L
24       R         R
25       R         R
26       R         R
27       L         L
28       L         L
29       R         R
..     ...       ...
158      R         R
159      L         L
160      L         L
161      R         R
162      R         R
163      L         L
164      L         L
165      L         L
166      R         R
167      L         L
168      R         R
169      R         R
170      L         L
171      R         R
172      L         B
173      R   

In [64]:
print(cm(Y_test, Y_pred_rfc))
print(cr(Y_test, Y_pred_rfc))

[[ 0  7  5]
 [ 7 79  1]
 [ 3  7 79]]
             precision    recall  f1-score   support

          B       0.00      0.00      0.00        12
          L       0.85      0.91      0.88        87
          R       0.93      0.89      0.91        89

avg / total       0.83      0.84      0.84       188



In [65]:
# Print Accuracy Score
print ("Accuracy is ", accuracy_score(Y_test,Y_pred_rfc)*100)

Accuracy is  84.04255319148936


In [66]:
model_entropy = RandomForestClassifier(criterion='entropy')
model_entropy.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [67]:
Y_pred_rfc_en = model_entropy.predict(X_test)

In [68]:
result = pd.DataFrame({'Actual': Y_test, 'Predicted':Y_pred_rfc_en})
print(result)

    Actual Predicted
0        R         R
1        L         L
2        B         R
3        R         R
4        L         L
5        L         L
6        R         R
7        B         R
8        L         L
9        R         R
10       R         R
11       R         R
12       R         L
13       R         R
14       L         L
15       L         B
16       R         R
17       R         R
18       R         R
19       L         L
20       R         R
21       R         R
22       L         L
23       L         L
24       R         R
25       R         R
26       R         R
27       L         L
28       L         L
29       R         R
..     ...       ...
158      R         R
159      L         L
160      L         L
161      R         B
162      R         R
163      L         L
164      L         L
165      L         L
166      R         R
167      L         L
168      R         R
169      R         R
170      L         L
171      R         R
172      L         B
173      R   

In [71]:
print(cm(Y_test, Y_pred_rfc_en))
print(cr(Y_test, Y_pred_rfc_en))

[[ 1  5  6]
 [11 76  0]
 [ 7  2 80]]
             precision    recall  f1-score   support

          B       0.05      0.08      0.06        12
          L       0.92      0.87      0.89        87
          R       0.93      0.90      0.91        89

avg / total       0.87      0.84      0.85       188



In [72]:
# Print Accuracy Score
print ("Accuracy is ", accuracy_score(Y_test,Y_pred_rfc_en)*100)

Accuracy is  83.51063829787235
