# Q.1- What is the probability of a person playing when the weather is sunny? Find P(Yes|Sunny).

                                Weather     Play
                                 Sunny       No
                                 Overcast    Yes
                                 Rainy       Yes
                                 Sunny       Yes
                                 Sunny       Yes
                                 Overcast    Yes
                                 Rainy       No
                                 Rainy       No
                                 Sunny       Yes
                                 Rainy       Yes
                                 Sunny       No
                                 Overcast    Yes
                                 Overcast    Yes
                                 Rainy       No

In [1]:
#Convert the data set into a frequency table

# probality of play yes when whether is sunny
sunny1=3
# probality of play no when the whether is sunny
sunny2=2
# probality of play yes when the whether is Overcast
overcast1=4
# probality of play no when the whether is Overcast
overcast2=0
# probality of play yes when the whether is Rainy
rainy1=2
# probality of play no when the whether is Rainy
rainy2=3

In [3]:
# Total Yes and No 
Total_yes=9
Total_no=5
Total= Total_yes + Total_no
print(Total)

14


In [15]:
# P(Yes | Sunny) = P( Sunny | Yes) * P(Yes) / P(Sunny)

# P( Sunny | Yes)
P= sunny1/Total_yes
print("P(Sunny|Yes)=",P)

# P(Yes)
p_yes= Total_yes/Total
print("P(Yes)=",p_yes)

# P(Sunny)
Total_sunny=5
P_sunny=Total_sunny/Total
print("P(Sunny)=",P_sunny)

# P(Yes | Sunny) = P( Sunny | Yes) * P(Yes) / P(Sunny)
# P(Yes) / P(Sunny)
A= p_yes/ P_sunny
print("P(Yes) / P(Sunny)=",A)
Prob = P*A
print("P(Yes|Sunny)=",Prob)


P(Sunny|Yes)= 0.3333333333333333
P(Yes)= 0.6428571428571429
P(Sunny)= 0.35714285714285715
P(Yes) / P(Sunny)= 1.8
P(Yes|Sunny)= 0.6


In [16]:
# Question 2.
import numpy as np
import pandas as pd

In [17]:
# Load datasets iris from sklearn
from sklearn.datasets import load_iris
data=load_iris()
x=data['data']
y=data['target']

In [18]:
from sklearn.model_selection import train_test_split as tts
train_x, test_x, train_y, test_y = tts(x, y, test_size = 0.2)

In [19]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(train_x, train_y)

GaussianNB(priors=None)

In [20]:
ypred = gnb.predict(test_x)

In [21]:
result=pd.DataFrame({'Actual':test_y,'Predicted':ypred})
print(result)

    Actual  Predicted
0        1          1
1        2          2
2        0          0
3        2          2
4        2          2
5        1          2
6        1          2
7        0          0
8        2          2
9        1          1
10       0          0
11       2          2
12       0          0
13       0          0
14       2          2
15       0          0
16       1          1
17       0          0
18       1          1
19       1          1
20       1          1
21       0          0
22       1          1
23       0          0
24       2          2
25       2          2
26       1          1
27       0          0
28       2          1
29       0          0


In [26]:
from sklearn.metrics import classification_report as cr, confusion_matrix as cm, r2_score as rs
print(cm(test_y,ypred))
print(cr(test_y,ypred))

[[11  0  0]
 [ 0  8  2]
 [ 0  1  8]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       0.89      0.80      0.84        10
          2       0.80      0.89      0.84         9

avg / total       0.90      0.90      0.90        30



In [27]:
print(rs(test_y,ypred)*100)

84.8993288590604


In [28]:
# Use MultinomialNB 
from sklearn.naive_bayes import MultinomialNB
model_MNB=MultinomialNB()

model_MNB.fit(train_x,train_y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [29]:
prediction_MNB=model_MNB.predict(test_x)

In [30]:
results_MNB=pd.DataFrame({'Prediction':prediction_MNB,'Actual':test_y})
print(results_MNB)

    Actual  Prediction
0        1           1
1        2           2
2        0           0
3        2           2
4        2           2
5        1           2
6        1           1
7        0           0
8        2           2
9        1           1
10       0           0
11       2           2
12       0           0
13       0           0
14       2           2
15       0           0
16       1           1
17       0           0
18       1           1
19       1           1
20       1           2
21       0           0
22       1           2
23       0           0
24       2           2
25       2           2
26       1           1
27       0           0
28       2           2
29       0           0


In [31]:
print(cm(test_y,prediction_MNB))
print(cr(test_y,prediction_MNB))

[[11  0  0]
 [ 0  7  3]
 [ 0  0  9]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       1.00      0.70      0.82        10
          2       0.75      1.00      0.86         9

avg / total       0.93      0.90      0.90        30



In [32]:
print(rs(test_y,prediction_MNB)*100)

84.8993288590604
