Q.1 - Create a numpy array with 10 elements of the shape(10,1) using np.random and find out the mean of the elements using basic numpy functions.

In [23]:
import numpy as np
a=np.random.random((10,1))
print(a)

[[0.47249294]
 [0.15361898]
 [0.10521221]
 [0.87373917]
 [0.55468523]
 [0.03574307]
 [0.16406102]
 [0.59019516]
 [0.70496488]
 [0.37552645]]


In [22]:
Mean=np.mean(a)
print (Mean)

0.5160894056407079


Q.2 - Create a numpy array with 20 elements of the shape(20,1) using np.random find the variance and standard deviation of the elements.

In [20]:

a=np.random.random((20,1))
print(a)


[[0.99635106]
 [0.06400698]
 [0.76113974]
 [0.20786069]
 [0.71627416]
 [0.66490054]
 [0.88099541]
 [0.46169734]
 [0.29505927]
 [0.76112929]
 [0.55349553]
 [0.31370213]
 [0.69096645]
 [0.01314716]
 [0.48405614]
 [0.81234905]
 [0.55531958]
 [0.39592001]
 [0.38480171]
 [0.30861587]]


In [19]:
Var=np.var(a)
print (Var)
Std=np.std(a)
print (Std)

0.06611105899661067
0.25712070899989886


Q.3 - Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25). Using basic numpy math functions only find the sum of all the elements of the new matrix.

In [25]:
A=np.random.random((10,20))
print(A)


[[0.01767446 0.56896088 0.34894905 0.86902016 0.44332712 0.67300909
  0.70525138 0.17284463 0.53345106 0.90466972 0.173198   0.11301402
  0.7950184  0.02846671 0.19619688 0.30818414 0.3473028  0.54186168
  0.78219068 0.83801904]
 [0.67970839 0.19175433 0.79311563 0.13112494 0.34896195 0.78803839
  0.92248031 0.98518196 0.85849123 0.19519897 0.56647052 0.50331098
  0.9549459  0.99447184 0.91502972 0.15289244 0.79093869 0.78165596
  0.21269465 0.30989368]
 [0.93130473 0.76237956 0.65410321 0.20599366 0.11022275 0.33657972
  0.38507192 0.12910679 0.5792964  0.43508083 0.37856398 0.78198858
  0.06005092 0.85246125 0.96967978 0.71547866 0.69205611 0.03716438
  0.57317361 0.60568705]
 [0.90407492 0.46943116 0.29623952 0.76186602 0.27779198 0.16336063
  0.24326775 0.36748948 0.91519648 0.09934459 0.56041753 0.02404239
  0.55233074 0.44325271 0.93681941 0.39654565 0.98127117 0.29804709
  0.71385089 0.17224432]
 [0.55368556 0.32404175 0.65405516 0.24854555 0.08242033 0.5638723
  0.37316143 0.03

In [31]:
B=np.random.random((20,25))
print(B)

[[0.47959361 0.55053731 0.03312658 0.94451405 0.96130964 0.47767377
  0.82459172 0.27364636 0.46076762 0.5625791  0.9734274  0.2229159
  0.13313922 0.29038647 0.16752337 0.20206605 0.50007131 0.62799957
  0.9656672  0.4240984  0.56876693 0.99551649 0.57108111 0.93999812
  0.04773955]
 [0.58186342 0.83952724 0.72568118 0.40297656 0.54626645 0.10472538
  0.60521351 0.45150483 0.34692204 0.44625124 0.20336325 0.55886971
  0.69171292 0.4343189  0.20956695 0.41239902 0.46045043 0.55589941
  0.5763078  0.16164716 0.93412005 0.38272096 0.6706196  0.53909655
  0.04846193]
 [0.23895472 0.60386586 0.01373973 0.9231101  0.70427961 0.68417197
  0.73849294 0.04604631 0.42085242 0.02732982 0.34463548 0.31267483
  0.94626061 0.00137414 0.71572407 0.89934873 0.18758681 0.02141281
  0.65404005 0.651895   0.74291843 0.77472778 0.65570332 0.70626893
  0.90937276]
 [0.6977367  0.42195042 0.23505351 0.33648581 0.29134898 0.06283364
  0.93957185 0.82246923 0.23608068 0.06664218 0.03831416 0.23504031
  0.945

In [32]:
print (A.dot(B))

[[4.78040367 4.36681082 3.49455396 4.21561428 3.78810407 3.32304822
  4.83752817 5.43416038 4.87037662 4.41761819 4.90519578 4.35169023
  5.29808973 5.06679748 5.45022234 4.72588212 4.96121159 5.14621135
  4.6410805  4.88789071 4.42339372 5.00796318 6.26244383 4.80253105
  4.41680856]
 [6.58204811 5.58984291 4.91113517 5.97062056 4.97674822 4.73056496
  5.40631575 6.35949916 6.89397068 5.46444922 5.9747186  5.61773481
  4.77511811 6.70220025 7.67248126 6.58447531 6.36794725 5.91317885
  6.5347636  5.80124893 5.53004162 8.24474835 7.48860162 6.14009263
  5.21226705]
 [5.78524941 5.0486451  3.85937923 5.56515835 5.81516129 4.48449747
  4.866263   5.55936851 4.59133253 4.74883359 5.1504302  4.70249058
  4.39051802 5.2488086  6.30109246 4.68589103 5.18880709 6.00387569
  5.58078963 4.68676587 5.85258201 7.01116991 7.14959763 4.99975455
  4.31093688]
 [5.42428042 4.46212639 3.8233171  4.80148941 5.04692337 3.58145838
  5.46431098 5.29089304 4.49459815 4.28034946 4.71386909 4.16562752
  4.25

In [34]:
m=np.ones((10,25))
print (m)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]]


In [36]:
SUM=sum(m)
print(SUM)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 10. 10. 10.]


Q.4 - Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) such that each element is the following function applied on each element of A. 

In [54]:
A=np.array([1,2,3,4,5,6,7,8,9,10])
print(A)

[ 1  2  3  4  5  6  7  8  9 10]


In [55]:
A +=3
print(A)





[ 4  5  6  7  8  9 10 11 12 13]


In [51]:
A -=3
print(A)

[ 1  2  3  4  5  6  7  8  9 10]


In [52]:
A *=3
print(A)

[ 3  6  9 12 15 18 21 24 27 30]


In [53]:
A **=2
print(A)

[  9  36  81 144 225 324 441 576 729 900]


In [57]:
A //=2
print(A)

[2 2 3 3 4 4 5 5 6 6]
