In [22]:
# question 1
import numpy as np
import pandas as pd

In [23]:
from sklearn.datasets import fetch_mldata
mnist = fetch_mldata('MNIST original')

In [24]:
print(mnist.data.shape)

(70000, 784)


In [25]:
X_raw = mnist['data']
y = mnist['target']

In [26]:
# Question 3
from sklearn.model_selection import train_test_split
# test_size: what proportion of original data is used for test set
train_x, test_x, train_y, test_y = train_test_split(X_raw, y, test_size=1/7.0, random_state=0)

In [27]:
# Question 2
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit on training set only.
X=scaler.fit(train_x)

C:\Users\Himashi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [28]:
# Question 4
from sklearn.decomposition import PCA
# Make an instance of the Model
pca = PCA(n_components=63)
pca.fit(train_x)

PCA(copy=True, iterated_power='auto', n_components=63, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [29]:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression(solver = 'lbfgs')

In [30]:
logisticRegr.fit(train_x, train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='lbfgs', tol=0.0001,
          verbose=0, warm_start=False)

In [31]:
 y_pred = logisticRegr.predict(test_x)

In [32]:
# Question 5.
from sklearn.metrics import confusion_matrix as cm, classification_report as cr

logisticRegr.score(test_x, test_y)

0.9131

In [33]:
print (cm(test_y, y_pred))

[[ 909    0    3    4    2    3    7    1    6    1]
 [   0 1121   10    4    1    4    4    2   14    3]
 [   3    9  874   17   13    3   16   14   31    2]
 [   1    6   32  929    0   25    2    7   24   12]
 [   6    1    5    0  871    2    9    4   10   40]
 [  12    4    9   37   11  778   19    5   34   12]
 [   4    1    5    1    5    9  982    0    5    1]
 [   8    3   15    3   12    1    0  942    5   40]
 [   5   20   10   30    6   30    9    4  849   15]
 [   7    2    4   19   40    5    0   28   11  876]]


In [34]:
print (cr(test_y, y_pred))

             precision    recall  f1-score   support

        0.0       0.95      0.97      0.96       936
        1.0       0.96      0.96      0.96      1163
        2.0       0.90      0.89      0.90       982
        3.0       0.89      0.89      0.89      1038
        4.0       0.91      0.92      0.91       948
        5.0       0.90      0.84      0.87       921
        6.0       0.94      0.97      0.95      1013
        7.0       0.94      0.92      0.93      1029
        8.0       0.86      0.87      0.86       978
        9.0       0.87      0.88      0.88       992

avg / total       0.91      0.91      0.91     10000

