In [21]:
# question 1
import pandas as pd
import numpy as np
import seaborn as sns

In [22]:
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [23]:
# Q.2- Split the dataset into training and testing sets using train_test_split() 
from sklearn.model_selection import train_test_split as tts
train, test = tts(iris, test_size = 0.2)

In [24]:
x_train = train.loc[:, train.columns != 'species']
x_test = test.loc[:, test.columns != 'species']

y_train = train['species']
y_test = test['species']

In [25]:
from sklearn.svm import SVC
model_linear = SVC(kernel = 'linear', degree = 8)
model_linear.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [26]:
y_pred= model_linear.predict(x_test)

Q.3- Use SVM with kernels 
a. Linear
b. Poly
c. Gaussian
d. Sigmoid
For every kernel, print the following:
a. Confusion Matrix
b. Classification Report

In [27]:
from sklearn.metrics import classification_report as cr, confusion_matrix as cm
print(cm(y_test, y_pred))
print(cr(y_test, y_pred))

[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        10
 versicolor       1.00      0.89      0.94         9
  virginica       0.92      1.00      0.96        11

avg / total       0.97      0.97      0.97        30



In [28]:
model_poly = SVC(kernel = 'poly', degree = 8)
model_poly.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [29]:
y_pred1= model_poly.predict(x_test)

In [30]:
print(cm(y_test, y_pred1))
print(cr(y_test, y_pred1))

[[10  0  0]
 [ 0  8  1]
 [ 0  1 10]]
             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        10
 versicolor       0.89      0.89      0.89         9
  virginica       0.91      0.91      0.91        11

avg / total       0.93      0.93      0.93        30



In [31]:
model_rbf = SVC(kernel = 'rbf', degree = 8)
model_rbf.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [32]:
y_pred2= model_rbf.predict(x_test)

In [33]:
print(cm(y_test, y_pred2))
print(cr(y_test, y_pred2))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        10
 versicolor       1.00      1.00      1.00         9
  virginica       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        30



In [34]:
model_sig = SVC(kernel = 'sigmoid', degree = 8)
model_sig .fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [35]:
y_pred3= model_sig .predict(x_test)

In [36]:
print(cm(y_test, y_pred3))
print(cr(y_test, y_pred3))

[[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]
             precision    recall  f1-score   support

     setosa       0.00      0.00      0.00        10
 versicolor       0.30      1.00      0.46         9
  virginica       0.00      0.00      0.00        11

avg / total       0.09      0.30      0.14        30



C:\Users\Himashi\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
